### ISSUE TITLE
Bad Number '2e308' on using Infinity

### ISSUE THREAD

**Issue by kssfilo** [marviq/coffee-jshint#28]
```
>echo Infinity>some.coffee
>coffee-jshint some.coffee
--------------------------------
some.coffee
1:1: Bad number '2e308'.
```

> CoffeeScript Changes 1.11.0 
> Just like undefined compiles to void 0,  NaN now compiles into 0/0 and  Infinity into 2e308.

This maybe problem of JSHint.  But no one use '2e308' but coffeescript users. 

Is it possible to workaround?

**Comment by jakubzitny** [comment]
@kssfilo I've updated the `errorsToSkip` array. You can manually edit it in `node_modules/coffee-jshint/lib-js/hint.js` or load it from my fork. Not sure how long / and if will it be merged.
